'use strict';
const KEY = 'difesa-riunioni-v1';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid = () => crypto.randomUUID ? crypto.randomUUID() : `id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const fields = ['title','date','time','location','protocol','chair','secretary','agenda','decisions','questions','next'];
const personFields = ['name','department','role','present','speaks','notes'];
const actionFields = ['department','proposer','type','description','outcome','owner','deadline','status'];
const agenda = 'Apertura e obiettivi della riunione\nInterventi dei tre reparti: attività e criticità\nNuove proposte e ampliamenti di reparto\nCoordinamento con il Dipartimento della Difesa\nRiepilogo, referenti e prossimi passi';
const seed = {id:'riunione-modello-001',title:'Riunione squadre di supporto',date:'2026-09-25',time:'21:30',location:'Discord del Governo',protocol:'UDC-001',chair:'Vice Segretario della Difesa Alexander Michigan',secretary:'Vice Segretario della Difesa Alexander Michigan',agenda,decisions:'',questions:'',next:'',people:[],actions:[],archived:false,updatedAt:'2026-09-25T00:00:00.000Z'};
let meetings = [], view = 'active', editing = null, dirty = false, storageBlocked = false, toastTimer;
function toast(message) { $('#toast').textContent=message; $('#toast').classList.add('visible'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000); }
function validRecords(data) {
  const stringFields = (obj, keys) => keys.every(k => typeof obj[k] === 'string' && obj[k].length <= 100000);
  return Array.isArray(data) && data.length <= 10000 && new Set(data.map(x=>x?.id)).size===data.length && data.every(m=>m && typeof m.id==='string' && m.id.length>0 && typeof m.archived==='boolean' && stringFields(m,fields) && typeof m.updatedAt==='string' && Array.isArray(m.people) && Array.isArray(m.actions) && m.people.every(p=>p && stringFields(p,personFields) && ['Da confermare','Sì','No'].includes(p.present) && ['No','Sì'].includes(p.speaks)) && m.actions.every(a=>a && stringFields(a,actionFields) && ['Problema','Proposta','Decisione','Azione'].includes(a.type) && ['Da fare','In corso','Completata'].includes(a.status)) && /^\d{4}-\d{2}-\d{2}$/.test(m.date));
}
try {const raw=localStorage.getItem(KEY); if(raw){meetings=JSON.parse(raw);if(!validRecords(meetings))throw Error('Formato non valido');}else{meetings=[structuredClone(seed)];localStorage.setItem(KEY,JSON.stringify(meetings));}} catch {storageBlocked=true;meetings=[];setTimeout(()=>toast('Archivio non disponibile. Nessun dato è stato sovrascritto. Controlla le impostazioni del browser.'),200);}
function persist(next){if(storageBlocked){toast('Salvataggio non disponibile: controlla lo spazio e le impostazioni del browser.');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));meetings=next;render();return true;}catch{toast('Salvataggio non riuscito. Libera spazio oppure esporta un backup.');return false;}}
function dateText(value){if(!value)return 'Data da definire';const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?value:d.toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'});}
function render(){
 const active=meetings.filter(m=>!m.archived).length, archived=meetings.length-active;
 $('#active-count').textContent=$('#stat-active').textContent=active;$('#archive-count').textContent=$('#stat-archived').textContent=archived;
 $('#stat-actions').textContent=meetings.filter(m=>!m.archived).reduce((n,m)=>n+m.actions.filter(a=>a.status!=='Completata').length,0);
 const isArchive=view==='archive';$('#page-title').textContent=isArchive?'Archivio personale':'Riunioni';$('#page-description').textContent=isArchive?'I verbali conservati, sempre consultabili e pronti da stampare.':'Ordini del giorno, presenze e decisioni. Tutto in un unico registro.';$('#list-title').textContent=isArchive?'Verbali archiviati':'Registro operativo';
 document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});
 const query=$('#search').value.trim().toLocaleLowerCase('it');
 const filtered=meetings.filter(m=>m.archived===isArchive && [m.title,m.protocol,m.location,m.chair,...m.people.map(p=>p.department),...m.actions.map(a=>a.department)].join(' ').toLocaleLowerCase('it').includes(query)).sort((a,b)=>b.date.localeCompare(a.date)||b.time.localeCompare(a.time));
 $('#meeting-list').innerHTML=filtered.length?`<div class="list-head"><span>OGGETTO / PROTOCOLLO</span><span>DATA E ORA</span><span>STATO</span><span></span></div>`+filtered.map(m=>`<div class="meeting-row"><div><button class="meeting-title" data-action="edit" data-id="${esc(m.id)}">${esc(m.title)}</button><div class="meeting-meta">${esc(m.protocol||'Senza protocollo')} · ${esc(m.location||'Luogo da definire')}</div></div><div class="meeting-date">${esc(dateText(m.date))}<small>${esc(m.time||'Orario da definire')}</small></div><div><span class="badge ${m.archived?'archived':''}">${m.archived?'Archiviata':'In lavorazione'}</span></div><div class="row-actions"><button data-action="edit" data-id="${esc(m.id)}">Apri scheda ↗</button><button data-action="print" data-id="${esc(m.id)}" aria-label="Stampa ${esc(m.title)}">Stampa</button><button data-action="archive" data-id="${esc(m.id)}">${m.archived?'Ripristina':'Archivia'}</button>${m.archived?`<button data-action="delete" data-id="${esc(m.id)}">Elimina</button>`:''}</div></div>`).join(''):`<div class="empty"><strong>${query?'Nessun risultato':isArchive?'Il tuo archivio inizia qui':'Il registro è pronto'}</strong>${query?'Prova con un altro oggetto, protocollo o reparto.':isArchive?'Archivia una riunione dal registro per conservarne il verbale.':'Crea una nuova riunione per iniziare a compilare il verbale.'}</div>`;
}
function input(label,key,value='',type='text',wide=false){return `<label${wide?' class="wide"':''}>${label}<input data-field="${key}" type="${type}" value="${esc(value)}" maxlength="10000"></label>`;}
function select(label,key,value,options){return `<label>${label}<select data-field="${key}">${options.map(o=>`<option${o===value?' selected':''}>${esc(o)}</option>`).join('')}</select></label>`;}
function area(label,key,value){return `<label class="wide">${label}<textarea data-field="${key}" rows="2">${esc(value)}</textarea></label>`;}
function addPerson(p={}){const card=document.createElement('div');card.className='repeat-card';card.innerHTML=`<div class="repeat-top"><span>PARTECIPANTE</span><button class="remove" type="button">Rimuovi</button></div><div class="repeat-fields">${input('Nome e cognome','name',p.name)}${input('Reparto','department',p.department)}${input('Ruolo','role',p.role)}${select('Presente?','present',p.present||'Da confermare',['Da confermare','Sì','No'])}${select('Intervento?','speaks',p.speaks||'No',['No','Sì'])}${input('Note','notes',p.notes)}</div>`;$('#people').append(card);card.querySelector('.remove').onclick=()=>{card.remove();dirty=true;};}
function addAction(a={}){const card=document.createElement('div');card.className='repeat-card';card.innerHTML=`<div class="repeat-top"><span>INTERVENTO / AZIONE</span><button class="remove" type="button">Rimuovi</button></div><div class="repeat-fields">${input('Reparto','department',a.department)}${input('Proponente','proposer',a.proposer)}${select('Tipo','type',a.type||'Proposta',['Problema','Proposta','Decisione','Azione'])}${area('Problema / proposta / decisione','description',a.description||'')}${area('Esito e prossimo passo','outcome',a.outcome||'')}${input('Responsabile','owner',a.owner)}${input('Scadenza','deadline',a.deadline,'date')}${select('Stato','status',a.status||'Da fare',['Da fare','In corso','Completata'])}</div>`;$('#actions').append(card);card.querySelector('.remove').onclick=()=>{card.remove();dirty=true;};}
function openEditor(id){const m=meetings.find(m=>m.id===id);editing=m?.id||null;$('#meeting-form').reset();fields.forEach(f=>$('#meeting-form').elements[f].value=m?.[f]||'');if(!m){const now=new Date();$('#meeting-form').elements.date.value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;$('#meeting-form').elements.agenda.value=agenda;}$('#editor-title').textContent=m?m.protocol||'Scheda riunione':'Nuova riunione';$('#people').innerHTML='';$('#actions').innerHTML='';m?.people.forEach(addPerson);m?.actions.forEach(addAction);dirty=false;$('#editor').showModal();$('#editor').scrollTop=0;}
function collectRows(selector,keys){return [...document.querySelectorAll(`${selector} .repeat-card`)].map(card=>Object.fromEntries(keys.map(k=>[k,card.querySelector(`[data-field="${k}"]`).value.trim()])));}
function confirmAction(title,message,callback){$('#confirm-title').textContent=title;$('#confirm-text').textContent=message;$('#confirm-dialog').showModal();$('#confirm-ok').onclick=()=>{$('#confirm-dialog').close();callback();};$('#confirm-cancel').onclick=()=>$('#confirm-dialog').close();}
function closeEditor(){if(dirty)confirmAction('Chiudere senza salvare?','Le modifiche a questa scheda andranno perse.',()=>{dirty=false;$('#editor').close();});else $('#editor').close();}
$('#meeting-form').addEventListener('input',()=>dirty=true);
$('#meeting-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const old=meetings.find(m=>m.id===editing);const m={id:editing||uuid(),archived:old?.archived||false,updatedAt:new Date().toISOString(),...Object.fromEntries(fields.map(f=>[f,form.elements[f].value.trim()])),people:collectRows('#people',personFields),actions:collectRows('#actions',actionFields)};if(!m.title){form.elements.title.focus();toast('Inserisci un oggetto per la riunione.');return;}if(persist(old?meetings.map(x=>x.id===m.id?m:x):[...meetings,m])){dirty=false;$('#editor').close();toast('Riunione salvata su questo dispositivo.');}});
$('#close-editor').onclick=closeEditor;$('#editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});$('#new-meeting').onclick=()=>openEditor();$('#add-person').onclick=()=>{addPerson();dirty=true;$('#people').lastElementChild.querySelector('input').focus();};$('#add-action').onclick=()=>{addAction();dirty=true;$('#actions').lastElementChild.querySelector('input').focus();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$('#search').value='';render();});$('#search').oninput=render;
$('#meeting-list').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const m=meetings.find(m=>m.id===b.dataset.id);if(!m)return;if(b.dataset.action==='edit')openEditor(m.id);if(b.dataset.action==='print')printMeeting(m);if(b.dataset.action==='archive'){if(persist(meetings.map(x=>x.id===m.id?{...x,archived:!x.archived,updatedAt:new Date().toISOString()}:x)))toast(m.archived?'Riunione ripristinata nel registro.':'Verbale spostato nell’archivio personale.');}if(b.dataset.action==='delete')confirmAction('Eliminare il verbale?',`“${m.title}” sarà eliminato da questo dispositivo. Puoi recuperarlo solo da un backup.`,()=>{if(persist(meetings.filter(x=>x.id!==m.id)))toast('Verbale eliminato.');});};
$('#backup').onclick=()=>{if(storageBlocked){toast('Archivio non leggibile: esportazione sospesa per evitare un backup incompleto.');return;}const blob=new Blob([JSON.stringify({app:'difesa-riunioni',version:1,exportedAt:new Date().toISOString(),meetings},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`difesa-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup esportato. Conservalo in un luogo personale.');};
$('#restore').onclick=()=>$('#backup-file').click();$('#backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>15000000)throw Error();const data=JSON.parse(await file.text());if(data.app!=='difesa-riunioni'||data.version!==1||!validRecords(data.meetings))throw Error();const imported=data.meetings.map(m=>({id:m.id,archived:m.archived,updatedAt:m.updatedAt,...Object.fromEntries(fields.map(f=>[f,m[f]])),people:m.people.map(p=>Object.fromEntries(personFields.map(f=>[f,p[f]]))),actions:m.actions.map(a=>Object.fromEntries(actionFields.map(f=>[f,a[f]])))}));confirmAction('Importare il backup?',`${imported.length} riunioni saranno aggiunte. Le schede con lo stesso identificativo saranno sostituite con quelle del backup. Le altre resteranno nell’archivio.`,()=>{const ids=new Set(imported.map(m=>m.id));if(persist([...meetings.filter(m=>!ids.has(m.id)),...imported]))toast('Backup importato.');});}catch{toast('File non valido. Seleziona un backup JSON esportato da questo portale.');}};
function table(headers,rows){return rows.length?`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p>Nessuna voce registrata.</p>';}
function printMeeting(m){$('#print-document').innerHTML=`<div class="print-head"><img src="assets/stemma-difesa.png" alt="Stemma della Difesa"><div><p>DIPARTIMENTO DELLA DIFESA · FIVEM ROLEPLAY</p><h1>Verbale di riunione</h1><p>${esc(m.protocol||'Senza protocollo')} · ${m.archived?'Archiviato':'In lavorazione'}</p></div></div><div class="print-section"><h2>${esc(m.title)}</h2></div><div class="print-data">${[['Data',dateText(m.date)],['Orario',m.time],['Luogo',m.location],['Protocollo',m.protocol],['Presiede',m.chair],['Verbalizza',m.secretary]].map(([k,v])=>`<div><b>${k}</b><br>${esc(v||'—')}</div>`).join('')}</div><section class="print-section"><h2>01 · Ordine del giorno</h2><ol>${m.agenda.split('\n').filter(x=>x.trim()).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><section class="print-section"><h2>02 · Presenze</h2>${table(['Nome e cognome','Reparto','Ruolo','Presente','Intervento','Note'],m.people.map(p=>personFields.map(k=>p[k])))}</section><section class="print-section"><h2>03 · Interventi e azioni</h2>${m.actions.length?m.actions.map((a,i)=>`<div><h3>${i+1}. ${esc(a.type)} · ${esc(a.department||'Reparto non indicato')}</h3><p><b>Proponente:</b> ${esc(a.proposer||'—')}<br><b>Problema / proposta / decisione:</b> ${esc(a.description||'—')}<br><b>Esito e prossimo passo:</b> ${esc(a.outcome||'—')}<br><b>Responsabile:</b> ${esc(a.owner||'—')} · <b>Scadenza:</b> ${esc(a.deadline?dateText(a.deadline):'—')} · <b>Stato:</b> ${esc(a.status)}</p></div>`).join(''):'<p>Nessun intervento registrato.</p>'}</section><section class="print-section"><h2>04 · Conclusioni</h2>${[['Decisioni confermate',m.decisions],['Questioni da approfondire',m.questions],['Prossimo aggiornamento / comunicazione',m.next]].map(([k,v])=>`<h3>${k}</h3><p>${esc(v||'Non indicato.')}</p>`).join('')}</section><div class="print-seal"><img src="assets/stemma-difesa.png" alt="Timbro del Dipartimento della Difesa"><p>DIPARTIMENTO DELLA DIFESA<br>Uso interno · FiveM Roleplay</p></div><div class="print-foot">Documento di gioco · Nessuna affiliazione con enti reali · Archivio personale</div>`;window.print();}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===KEY){storageBlocked=true;toast('Archivio modificato in un’altra scheda. Copia eventuali modifiche e ricarica prima di salvare.');}});
render();
