'use strict';
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const STORAGE_KEY = 'difesa-sanzioni-v1';
const recordFields = ['member','memberId','department','role','articleId','protocol','date','reason','amount','internal','issuer','status','start','end','notes'];
const articleFields = ['id','group','level','title','description','administrative','internal'];
const statuses = ['In corso','Eseguita','Revocata'];
let sanctions = [], blocked = false, editingId = null, dirty = false, reference = null, timer;
const dateText = value => value ? new Date(value + 'T12:00:00').toLocaleDateString('it-IT') : '—';
const money = value => value === '' ? 'Non applicabile' : Number(value).toLocaleString('it-IT', {maximumFractionDigits:2}) + ' $ RP';
const today = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function notify(message) {$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),5500);}
function isDate(value) {if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+'T12:00:00Z');return !Number.isNaN(d.getTime()) && d.toISOString().slice(0,10)===value;}
function validRecords(records) {
  return Array.isArray(records) && records.length<=10000 && records.every(r=>r && typeof r==='object') && new Set(records.map(r=>r.id)).size===records.length && records.every(r=>
    typeof r.id==='string' && r.id.length>0 && r.id.length<=150 && recordFields.every(k=>typeof r[k]==='string' && r[k].length<=20000) &&
    ['member','memberId','department','protocol','reason','issuer'].every(k=>r[k].trim()) && statuses.includes(r.status) && isDate(r.date) &&
    (!r.start||isDate(r.start)) && (!r.end||isDate(r.end)) && (!r.start||!r.end||r.end>=r.start) &&
    (r.amount==='' || (/^\d+(\.\d{1,2})?$/.test(r.amount) && Number(r.amount)<=1000000000)) && (r.amount!==''||r.internal.trim()) &&
    typeof r.updatedAt==='string' && typeof r.codeVersion==='string' && r.codeVersion.length<=250 &&
    r.article && articleFields.every(k=>typeof r.article[k]==='string' && r.article[k].length<=20000) && r.article.id===r.articleId);
}
try {const raw=localStorage.getItem(STORAGE_KEY);if(raw){const data=JSON.parse(raw);if(!validRecords(data))throw Error();sanctions=data;}}catch{blocked=true;setTimeout(()=>notify('Archivio sanzioni non leggibile. I dati esistenti non sono stati sovrascritti.'),100);}
function saveRecords(next){if(blocked){notify('Salvataggio bloccato: controlla il browser o ricarica se l’archivio è cambiato in un’altra scheda.');return false;}try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));sanctions=next;renderRegister();return true;}catch{notify('Salvataggio non riuscito. Esporta un backup e controlla lo spazio del browser.');return false;}}
function confirmAction(title,text,action){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;$('#confirm-dialog').showModal();$('#confirm-ok').onclick=()=>{$('#confirm-dialog').close();action();};$('#confirm-cancel').onclick=()=>$('#confirm-dialog').close();}
function setTab(tab){const code=tab==='code';$('#register-panel').hidden=code;$('#code-panel').hidden=!code;$('#discipline-title').textContent=code?'CCDPAD':'Registro sanzioni';document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});history.replaceState(null,'',code?'#codice':'#sanzioni');}
function renderRegister(){
  $('#sanction-count').textContent=$('#total-sanctions').textContent=sanctions.length;
  $('#active-sanctions').textContent=sanctions.filter(r=>r.status==='In corso').length;
  $('#total-members').textContent=new Set(sanctions.map(r=>r.memberId.trim().toLowerCase())).size;
  const query=$('#sanction-search').value.trim().toLowerCase(), status=$('#status-filter').value;
  const list=sanctions.filter(r=>(!status||r.status===status) && [r.member,r.memberId,r.department,r.protocol,r.articleId,r.article.title].join(' ').toLowerCase().includes(query)).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));
  $('#sanction-list').innerHTML=list.length?list.map(r=>`<div class="sanction-row"><div><button class="meeting-title" data-action="edit" data-id="${escapeHtml(r.id)}">${escapeHtml(r.member)}</button><div class="meeting-meta">ID ${escapeHtml(r.memberId)} · ${escapeHtml(r.department)}</div><div class="meeting-meta">${escapeHtml(r.protocol)} · ${dateText(r.date)}</div></div><div><span class="badge">${escapeHtml(r.articleId)} · ${escapeHtml(r.article.level)}</span><p class="sanction-measure">${escapeHtml(r.internal||'Nessuna misura interna')}<br><span>${escapeHtml(money(r.amount))}</span></p></div><span class="badge ${r.status==='Revocata'?'archived':''}">${escapeHtml(r.status)}</span><div class="row-actions"><button data-action="edit" data-id="${escapeHtml(r.id)}">Apri scheda ↗</button><button data-action="print" data-id="${escapeHtml(r.id)}">Stampa</button><button data-action="delete" data-id="${escapeHtml(r.id)}">Elimina</button></div></div>`).join(''):`<div class="empty"><strong>${sanctions.length?'Nessun risultato':'Nessuna sanzione registrata'}</strong>${sanctions.length?'Modifica la ricerca o il filtro di stato.':'Registra un provvedimento e associalo al membro interessato.'}</div>`;
}
function referenceMarkup(a,version=CCDPAD.version){return `<div class="article-meta"><span class="badge">${escapeHtml(a.id)} · ${escapeHtml(a.level)}</span><span>${escapeHtml(a.group)} · ${escapeHtml(version)}</span></div><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.description)}</p><div class="penalties"><div><strong>Sanzione amministrativa prevista</strong><p>${escapeHtml(a.administrative)}</p></div><div><strong>Sanzioni interne previste</strong><p>${escapeHtml(a.internal)}</p></div></div>`;}
function renderCode(){const query=$('#code-search').value.trim().toLowerCase(),group=$('#group-filter').value,level=$('#level-filter').value;const articles=CCDPAD.articles.filter(a=>(!group||a.group===group)&&(!level||a.level===level)&&[a.id,a.title,a.description].join(' ').toLowerCase().includes(query));$('#article-count').textContent=`${articles.length} articoli su ${CCDPAD.articles.length}`;$('#article-list').innerHTML=articles.map(a=>`<article class="code-article">${referenceMarkup(a)}<button class="button small" data-article="${escapeHtml(a.id)}">Registra sanzione per questo articolo</button></article>`).join('')||'<div class="empty">Nessun articolo corrisponde ai filtri.</div>';}
function openEditor(id,articleId){const r=sanctions.find(x=>x.id===id);editingId=r?.id||null;const form=$('#sanction-form');form.reset();recordFields.forEach(k=>form.elements[k].value=r?.[k]||'');const options=CCDPAD.articles.map(a=>`<option value="${escapeHtml(a.id)}">${escapeHtml(a.id+' · '+a.title)}</option>`);if(r&&!CCDPAD.articles.some(a=>a.id===r.articleId))options.push(`<option value="${escapeHtml(r.articleId)}">${escapeHtml(r.articleId)} · Riferimento salvato</option>`);$('#article-select').innerHTML='<option value="">Seleziona un articolo</option>'+options.join('');form.elements.articleId.value=r?.articleId||articleId||'';if(!r){form.elements.date.value=today();form.elements.status.value='In corso';}reference=r?{article:structuredClone(r.article),version:r.codeVersion}:null;updateReference();$('#sanction-editor-title').textContent=r?'Modifica sanzione':'Registra sanzione';dirty=false;$('#sanction-editor').showModal();$('#sanction-editor').scrollTop=0;}
function updateReference(){const id=$('#article-select').value;if(reference?.article.id!==id){const a=CCDPAD.articles.find(a=>a.id===id);reference=a?{article:structuredClone(a),version:CCDPAD.version}:null;}$('#article-preview').innerHTML=reference?referenceMarkup(reference.article,reference.version):'<p>Seleziona un articolo per consultare descrizione e sanzioni previste.</p>';}
function closeEditor(){if(dirty)confirmAction('Chiudere senza salvare?','Le modifiche alla sanzione andranno perse.',()=>{dirty=false;$('#sanction-editor').close();});else $('#sanction-editor').close();}
$('#sanction-form').addEventListener('input',()=>dirty=true);
$('#article-select').onchange=()=>{dirty=true;updateReference();};
$('#sanction-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;const r={id:editingId||crypto.randomUUID(),...Object.fromEntries(recordFields.map(k=>[k,form.elements[k].value.trim()])),article:reference?.article,codeVersion:reference?.version,updatedAt:new Date().toISOString()};if(r.start&&r.end&&r.end<r.start){notify('La scadenza deve essere uguale o successiva alla decorrenza.');return;}if(r.amount===''&&!r.internal){notify('Indica almeno un importo o una sanzione interna applicata.');return;}if(!validRecords([r])){notify('Controlla i campi obbligatori, l’articolo e le date.');return;}if(saveRecords(editingId?sanctions.map(s=>s.id===editingId?r:s):[...sanctions,r])){dirty=false;$('#sanction-editor').close();notify('Sanzione salvata su questo dispositivo.');}};
function printRecord(r){$('#print-document').innerHTML=`<div class="print-head"><img src="assets/stemma-difesa.png" alt="Stemma della Difesa"><div><p>DIPARTIMENTO DELLA DIFESA · FIVEM ROLEPLAY</p><h1>Provvedimento disciplinare</h1><p>${escapeHtml(r.protocol)} · ${dateText(r.date)}</p></div></div><div class="print-data">${[['Membro',r.member],['Matricola / ID',r.memberId],['Reparto',r.department],['Grado / incarico',r.role],['Disposto da',r.issuer],['Stato',r.status],['Decorrenza',dateText(r.start)],['Scadenza',dateText(r.end)]].map(([k,v])=>`<div><b>${k}</b><br>${escapeHtml(v||'—')}</div>`).join('')}</div><section class="print-section"><h2>Riferimento al CCDPAD</h2>${referenceMarkup(r.article,r.codeVersion)}</section>${[['Motivazione e fatti accertati',r.reason],['Sanzione amministrativa applicata',money(r.amount)],['Sanzione interna applicata',r.internal||'Non applicabile'],['Note e riferimenti agli atti',r.notes||'—']].map(([k,v])=>`<section class="print-section"><h2>${k}</h2><p>${escapeHtml(v)}</p></section>`).join('')}<div class="print-seal"><img src="assets/stemma-difesa.png" alt="Timbro della Difesa"><p>DIPARTIMENTO DELLA DIFESA<br>Uso interno · FiveM Roleplay</p></div><div class="print-foot">Documento di gioco · Riferimento al codice conservato al momento della registrazione · Nessuna affiliazione con enti reali</div>`;window.print();}
$('#sanction-list').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const r=sanctions.find(s=>s.id===b.dataset.id);if(!r)return;if(b.dataset.action==='edit')openEditor(r.id);if(b.dataset.action==='print')printRecord(r);if(b.dataset.action==='delete')confirmAction('Eliminare la registrazione?',`La sanzione ${r.protocol} di ${r.member} sarà eliminata. Per conservare lo storico di un provvedimento revocato, modifica invece lo stato in “Revocata”.`,()=>{if(saveRecords(sanctions.filter(s=>s.id!==r.id)))notify('Registrazione eliminata.');});};
$('#export-sanctions').onclick=()=>{if(blocked){notify('Archivio non leggibile: esportazione sospesa per evitare backup incompleti.');return;}const blob=new Blob([JSON.stringify({app:'difesa-sanzioni',version:1,exportedAt:new Date().toISOString(),sanctions},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`difesa-sanzioni-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#import-sanctions').onclick=()=>$('#sanction-file').click();
$('#sanction-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>15000000)throw Error();const data=JSON.parse(await file.text());if(data.app!=='difesa-sanzioni'||data.version!==1||!validRecords(data.sanctions))throw Error();const imported=data.sanctions.map(r=>({...Object.fromEntries(['id','updatedAt','codeVersion',...recordFields].map(k=>[k,r[k]])),article:Object.fromEntries(articleFields.map(k=>[k,r.article[k]]))}));confirmAction('Importare le sanzioni?',`${imported.length} registrazioni saranno importate. Quelle con lo stesso identificativo saranno sostituite, le altre conservate. Le riunioni non saranno modificate.`,()=>{const ids=new Set(imported.map(r=>r.id));if(saveRecords([...sanctions.filter(r=>!ids.has(r.id)),...imported]))notify('Backup sanzioni importato.');});}catch{notify('File non valido. Seleziona un backup sanzioni esportato da questa sezione.');}};
$('#new-sanction').onclick=()=>openEditor();$('#close-sanction').onclick=closeEditor;$('#sanction-editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});
$('#article-list').onclick=e=>{const b=e.target.closest('[data-article]');if(b)openEditor(null,b.dataset.article);};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('#sanction-search').oninput=renderRegister;$('#status-filter').onchange=renderRegister;$('#code-search').oninput=renderCode;$('#group-filter').onchange=renderCode;$('#level-filter').onchange=renderCode;
$('#code-version').textContent=CCDPAD.version;$('#code-approval').textContent=CCDPAD.approval;$('#code-classification').textContent=CCDPAD.classification;$('#code-full-title').textContent=CCDPAD.title;$('#code-subtitle').textContent=CCDPAD.subtitle;$('#code-notes').innerHTML=CCDPAD.notes.map(n=>`<dt>${escapeHtml(n.level)}</dt><dd>${escapeHtml(n.text)}</dd>`).join('');
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY||e.key===null){blocked=true;notify('Archivio modificato in un’altra scheda. Conserva le modifiche e ricarica prima di salvare.');}});
renderRegister();renderCode();setTab(location.hash==='#codice'?'code':'register');
